### ISSUE TITLE
Failed to run, maybe caused by parsing annotations.json

### ISSUE THREAD

**Issue by QuantumLiu** [anuragxel/salt#28]
```
python segment_anything_annotator.py --onnx-models-path models --dataset-path seg_imgs --categories dog
Traceback (most recent call last):
  File "segment_anything_annotator.py", line 26, in <module>
    editor = Editor(
  File "C:\pyprojects\salt\salt\editor.py", line 45, in __init__
    self.dataset_explorer = DatasetExplorer(
  File "C:\pyprojects\salt\salt\dataset_explorer.py", line 126, in __init__
    max(self.coco_json["annotations"], key=lambda x: x["id"])["id"] + 1
ValueError: max() arg is an empty sequence
```

![image](https://user-images.githubusercontent.com/21980268/232570973-3ec09fde-443f-4715-b4fb-12037b56672a.png)
![image](https://user-images.githubusercontent.com/21980268/232571146-d613a212-cc1a-4784-8417-1e5f6458dd63.png)

**Comment by anuragxel** [comment]
I reverted a recent merge, can you try now?

**Comment by QuantumLiu** [comment]
> I reverted a recent merge, can you try now?

Worked for me on Linux
